version: '2'

services:

  filebeat:
    image: gaven/filebeat
    container_name: filebeat
    restart: always
    volumes:
      - ../external_config/filebeat/filebeat.yml:/filebeat.yml
      - /opt/log/stash:/input
    depends_on:
      - elasticsearch

