version: '2'

services:

  mysql:
    image: mysql:5.6
    container_name: mysql
    restart: always
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --character-set-client-handshake=0
    volumes:
      - ../data_storage/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_ROOT_PASSWORD=root

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    volumes:
      - ../data_storage/redis:/data
    ports:
      - 6379:6379

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    restart: always
    volumes:
      - ../data_storage/rabbitmq:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  kafka:
    image: gaven/kafka
    container_name: kafka
    restart: always
    ports:
      - 2181:2181
      - 9092:9092
      - 9000:9000
      - 18081:8081
    environment:
      - ADVERTISED_HOST=localhost
      - ADVERTISED_PORT=9092

  elasticsearch:
    image: elasticsearch:alpine
    container_name: elasticsearch
    restart: always
    volumes:
      - ../data_storage/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    # environment:
    #   - http.host=0.0.0.0
    #   - transport.host=127.0.0.1

  nexus:
    image: sonatype/nexus3
    container_name: nexus
    restart: always
    volumes:
      # chown -R 200 ../data_storage/nexus
      - ../data_storage/nexus:/nexus-data
    ports:
      - 8081:8081

  kibana:
    image: kibana
    container_name: kibana
    restart: always
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch